services:
  mysql_db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - ./data/docker/mysql:/var/lib/mysql
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123"
    ports:
      - "1433:1433"
    volumes:
      - ./data/docker/sqlserver:/var/opt/mssql
  postgres_db:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/docker/postgres:/var/lib/postgresql/data
